name: Persistent Habblive Login
on:
  workflow_dispatch:

jobs:
  persistent-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instala dependências
        run: |
          pip install selenium webdriver-manager colorama

      - name: Executa login persistente com painel e ações
        env:
          HABBLIVE_USERNAME_2: ${{ secrets.HABBLIVE_USERNAME_2 }}
          HABBLIVE_PASSWORD_2: ${{ secrets.HABBLIVE_PASSWORD_2 }}
          HABBLIVE_USERNAME_3: ${{ secrets.HABBLIVE_USERNAME_3 }}
          HABBLIVE_PASSWORD_3: ${{ secrets.HABBLIVE_PASSWORD_3 }}
          HABBLIVE_USERNAME_4: ${{ secrets.HABBLIVE_USERNAME_4 }}
          HABBLIVE_PASSWORD_4: ${{ secrets.HABBLIVE_PASSWORD_4 }}
          HABBLIVE_USERNAME_5: ${{ secrets.HABBLIVE_USERNAME_5 }}
          HABBLIVE_PASSWORD_5: ${{ secrets.HABBLIVE_PASSWORD_5 }}
          HABBLIVE_USERNAME_6: ${{ secrets.HABBLIVE_USERNAME_6 }}
          HABBLIVE_PASSWORD_6: ${{ secrets.HABBLIVE_PASSWORD_6 }}
          HABBLIVE_USERNAME_7: ${{ secrets.HABBLIVE_USERNAME_7 }}
          HABBLIVE_PASSWORD_7: ${{ secrets.HABBLIVE_PASSWORD_7 }}
          HABBLIVE_USERNAME_8: ${{ secrets.HABBLIVE_USERNAME_8 }}
          HABBLIVE_PASSWORD_8: ${{ secrets.HABBLIVE_PASSWORD_8 }}
          HABBLIVE_USERNAME_9: ${{ secrets.HABBLIVE_USERNAME_9 }}
          HABBLIVE_PASSWORD_9: ${{ secrets.HABBLIVE_PASSWORD_9 }}
          HABBLIVE_USERNAME_10: ${{ secrets.HABBLIVE_USERNAME_10 }}
          HABBLIVE_PASSWORD_10: ${{ secrets.HABBLIVE_PASSWORD_10 }}
          HABBLIVE_USERNAME_11: ${{ secrets.HABBLIVE_USERNAME_11 }}
          HABBLIVE_PASSWORD_11: ${{ secrets.HABBLIVE_PASSWORD_11 }}
          HABBLIVE_USERNAME_12: ${{ secrets.HABBLIVE_USERNAME_12 }}
          HABBLIVE_PASSWORD_12: ${{ secrets.HABBLIVE_PASSWORD_12 }}
          HABBLIVE_USERNAME_13: ${{ secrets.HABBLIVE_USERNAME_13 }}
          HABBLIVE_PASSWORD_13: ${{ secrets.HABBLIVE_PASSWORD_13 }}
          HABBLIVE_USERNAME_14: ${{ secrets.HABBLIVE_USERNAME_14 }}
          HABBLIVE_PASSWORD_14: ${{ secrets.HABBLIVE_PASSWORD_14 }}
          HABBLIVE_USERNAME_15: ${{ secrets.HABBLIVE_USERNAME_15 }}
          HABBLIVE_PASSWORD_15: ${{ secrets.HABBLIVE_PASSWORD_15 }}
          HABBLIVE_USERNAME_16: ${{ secrets.HABBLIVE_USERNAME_16 }}
          HABBLIVE_PASSWORD_16: ${{ secrets.HABBLIVE_PASSWORD_16 }}
          HABBLIVE_USERNAME_17: ${{ secrets.HABBLIVE_USERNAME_17 }}
          HABBLIVE_PASSWORD_17: ${{ secrets.HABBLIVE_PASSWORD_17 }}
          HABBLIVE_USERNAME_18: ${{ secrets.HABBLIVE_USERNAME_18 }}
          HABBLIVE_PASSWORD_18: ${{ secrets.HABBLIVE_PASSWORD_18 }}
          HABBLIVE_USERNAME_19: ${{ secrets.HABBLIVE_USERNAME_19 }}
          HABBLIVE_PASSWORD_19: ${{ secrets.HABBLIVE_PASSWORD_19 }}
          HABBLIVE_USERNAME_20: ${{ secrets.HABBLIVE_USERNAME_20 }}
          HABBLIVE_PASSWORD_20: ${{ secrets.HABBLIVE_PASSWORD_20 }}
          HABBLIVE_USERNAME_21: ${{ secrets.HABBLIVE_USERNAME_21 }}
          HABBLIVE_PASSWORD_21: ${{ secrets.HABBLIVE_PASSWORD_21 }}
          HABBLIVE_USERNAME_22: ${{ secrets.HABBLIVE_USERNAME_22 }}
          HABBLIVE_PASSWORD_22: ${{ secrets.HABBLIVE_PASSWORD_22 }}
          HABBLIVE_USERNAME_23: ${{ secrets.HABBLIVE_USERNAME_23 }}
          HABBLIVE_PASSWORD_23: ${{ secrets.HABBLIVE_PASSWORD_23 }}
          HABBLIVE_USERNAME_24: ${{ secrets.HABBLIVE_USERNAME_24 }}
          HABBLIVE_PASSWORD_24: ${{ secrets.HABBLIVE_PASSWORD_24 }}
          HABBLIVE_USERNAME_25: ${{ secrets.HABBLIVE_USERNAME_25 }}
          HABBLIVE_PASSWORD_25: ${{ secrets.HABBLIVE_PASSWORD_25 }}
          HABBLIVE_USERNAME_26: ${{ secrets.HABBLIVE_USERNAME_26 }}
          HABBLIVE_PASSWORD_26: ${{ secrets.HABBLIVE_PASSWORD_26 }}
          HABBLIVE_USERNAME_27: ${{ secrets.HABBLIVE_USERNAME_27 }}
          HABBLIVE_PASSWORD_27: ${{ secrets.HABBLIVE_PASSWORD_27 }}
          HABBLIVE_USERNAME_28: ${{ secrets.HABBLIVE_USERNAME_28 }}
          HABBLIVE_PASSWORD_28: ${{ secrets.HABBLIVE_PASSWORD_28 }}
          HABBLIVE_USERNAME_29: ${{ secrets.HABBLIVE_USERNAME_29 }}
          HABBLIVE_PASSWORD_29: ${{ secrets.HABBLIVE_PASSWORD_29 }}
          HABBLIVE_USERNAME_30: ${{ secrets.HABBLIVE_USERNAME_30 }}
          HABBLIVE_PASSWORD_30: ${{ secrets.HABBLIVE_PASSWORD_30 }}
          HABBLIVE_USERNAME_31: ${{ secrets.HABBLIVE_USERNAME_31 }}
          HABBLIVE_PASSWORD_31: ${{ secrets.HABBLIVE_PASSWORD_31 }}
          HABBLIVE_USERNAME_32: ${{ secrets.HABBLIVE_USERNAME_32 }}
          HABBLIVE_PASSWORD_32: ${{ secrets.HABBLIVE_PASSWORD_32 }}
          HABBLIVE_USERNAME_33: ${{ secrets.HABBLIVE_USERNAME_33 }}
          HABBLIVE_PASSWORD_33: ${{ secrets.HABBLIVE_PASSWORD_33 }}
          HABBLIVE_USERNAME_34: ${{ secrets.HABBLIVE_USERNAME_34 }}
          HABBLIVE_PASSWORD_34: ${{ secrets.HABBLIVE_PASSWORD_34 }}
          HABBLIVE_USERNAME_35: ${{ secrets.HABBLIVE_USERNAME_35 }}
          HABBLIVE_PASSWORD_35: ${{ secrets.HABBLIVE_PASSWORD_35 }}
          HABBLIVE_USERNAME_36: ${{ secrets.HABBLIVE_USERNAME_36 }}
          HABBLIVE_PASSWORD_36: ${{ secrets.HABBLIVE_PASSWORD_36 }}
          HABBLIVE_USERNAME_37: ${{ secrets.HABBLIVE_USERNAME_37 }}
          HABBLIVE_PASSWORD_37: ${{ secrets.HABBLIVE_PASSWORD_37 }}
          HABBLIVE_USERNAME_38: ${{ secrets.HABBLIVE_USERNAME_38 }}
          HABBLIVE_PASSWORD_38: ${{ secrets.HABBLIVE_PASSWORD_38 }}
          HABBLIVE_USERNAME_39: ${{ secrets.HABBLIVE_USERNAME_39 }}
          HABBLIVE_PASSWORD_39: ${{ secrets.HABBLIVE_PASSWORD_39 }}
          HABBLIVE_USERNAME_40: ${{ secrets.HABBLIVE_USERNAME_40 }}
          HABBLIVE_PASSWORD_40: ${{ secrets.HABBLIVE_PASSWORD_40 }}
          HABBLIVE_USERNAME_41: ${{ secrets.HABBLIVE_USERNAME_41 }}
          HABBLIVE_PASSWORD_41: ${{ secrets.HABBLIVE_PASSWORD_41 }}
          HABBLIVE_USERNAME_42: ${{ secrets.HABBLIVE_USERNAME_42 }}
          HABBLIVE_PASSWORD_42: ${{ secrets.HABBLIVE_PASSWORD_42 }}
          HABBLIVE_USERNAME_43: ${{ secrets.HABBLIVE_USERNAME_43 }}
          HABBLIVE_PASSWORD_43: ${{ secrets.HABBLIVE_PASSWORD_43 }}
          HABBLIVE_USERNAME_44: ${{ secrets.HABBLIVE_USERNAME_44 }}
          HABBLIVE_PASSWORD_44: ${{ secrets.HABBLIVE_PASSWORD_44 }}
          HABBLIVE_USERNAME_45: ${{ secrets.HABBLIVE_USERNAME_45 }}
          HABBLIVE_PASSWORD_45: ${{ secrets.HABBLIVE_PASSWORD_45 }}
          HABBLIVE_USERNAME_46: ${{ secrets.HABBLIVE_USERNAME_46 }}
          HABBLIVE_PASSWORD_46: ${{ secrets.HABBLIVE_PASSWORD_46 }}
          HABBLIVE_USERNAME_47: ${{ secrets.HABBLIVE_USERNAME_47 }}
          HABBLIVE_PASSWORD_47: ${{ secrets.HABBLIVE_PASSWORD_47 }}
          HABBLIVE_USERNAME_48: ${{ secrets.HABBLIVE_USERNAME_48 }}
          HABBLIVE_PASSWORD_48: ${{ secrets.HABBLIVE_PASSWORD_48 }}
          HABBLIVE_USERNAME_49: ${{ secrets.HABBLIVE_USERNAME_49 }}
          HABBLIVE_PASSWORD_49: ${{ secrets.HABBLIVE_PASSWORD_49 }}
          HABBLIVE_USERNAME_50: ${{ secrets.HABBLIVE_USERNAME_50 }}
          HABBLIVE_PASSWORD_50: ${{ secrets.HABBLIVE_PASSWORD_50 }}
          # Adicione mais pares conforme necessário
        run: python persistent_login.py
