name: Persistent Login (Contas 21-30)

on:
  workflow_dispatch:

jobs:
  login-21-30:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install selenium webdriver-manager colorama
      - name: Executa login persistente
        env:
          HABBLIVE_USERNAME_21: ${{ secrets.HABBLIVE_USERNAME_21 }}
          HABBLIVE_PASSWORD_21: ${{ secrets.HABBLIVE_PASSWORD_21 }}
          HABBLIVE_USERNAME_22: ${{ secrets.HABBLIVE_USERNAME_22 }}
          HABBLIVE_PASSWORD_22: ${{ secrets.HABBLIVE_PASSWORD_22 }}
          HABBLIVE_USERNAME_23: ${{ secrets.HABBLIVE_USERNAME_23 }}
          HABBLIVE_PASSWORD_23: ${{ secrets.HABBLIVE_PASSWORD_23 }}
          HABBLIVE_USERNAME_24: ${{ secrets.HABBLIVE_USERNAME_24 }}
          HABBLIVE_PASSWORD_24: ${{ secrets.HABBLIVE_PASSWORD_24 }}
          HABBLIVE_USERNAME_25: ${{ secrets.HABBLIVE_USERNAME_25 }}
          HABBLIVE_PASSWORD_25: ${{ secrets.HABBLIVE_PASSWORD_25 }}
          HABBLIVE_USERNAME_26: ${{ secrets.HABBLIVE_USERNAME_26 }}
          HABBLIVE_PASSWORD_26: ${{ secrets.HABBLIVE_PASSWORD_26 }}
          HABBLIVE_USERNAME_27: ${{ secrets.HABBLIVE_USERNAME_27 }}
          HABBLIVE_PASSWORD_27: ${{ secrets.HABBLIVE_PASSWORD_27 }}
          HABBLIVE_USERNAME_28: ${{ secrets.HABBLIVE_USERNAME_28 }}
          HABBLIVE_PASSWORD_28: ${{ secrets.HABBLIVE_PASSWORD_28 }}
          HABBLIVE_USERNAME_29: ${{ secrets.HABBLIVE_USERNAME_29 }}
          HABBLIVE_PASSWORD_29: ${{ secrets.HABBLIVE_PASSWORD_29 }}
          HABBLIVE_USERNAME_30: ${{ secrets.HABBLIVE_USERNAME_30 }}
          HABBLIVE_PASSWORD_30: ${{ secrets.HABBLIVE_PASSWORD_30 }}
        run: python persistent_login.py

      - name: Reiniciar workflow automaticamente
        if: ${{ vars.HABILITAR_REINICIO == 'true' }}
        run: |
          echo "Reiniciando workflow automaticamente..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml/dispatches \
            -d '{"ref":"${{ github.ref_name }}"}'
