name: Persistent Habblive Login
on:
  workflow_dispatch:

jobs:
  persistent-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instala dependências
        run: |
          pip install selenium webdriver-manager colorama

      - name: Executa login persistente com painel e ações
        env:
          HABBLIVE_USERNAME_2: ${{ secrets.HABBLIVE_USERNAME_2 }}
          HABBLIVE_PASSWORD_2: ${{ secrets.HABBLIVE_PASSWORD_2 }}
          HABBLIVE_USERNAME_3: ${{ secrets.HABBLIVE_USERNAME_3 }}
          HABBLIVE_PASSWORD_3: ${{ secrets.HABBLIVE_PASSWORD_3 }}
          HABBLIVE_USERNAME_4: ${{ secrets.HABBLIVE_USERNAME_4 }}
          HABBLIVE_PASSWORD_4: ${{ secrets.HABBLIVE_PASSWORD_4 }}
          HABBLIVE_USERNAME_5: ${{ secrets.HABBLIVE_USERNAME_5 }}
          HABBLIVE_PASSWORD_5: ${{ secrets.HABBLIVE_PASSWORD_5 }}
          HABBLIVE_USERNAME_6: ${{ secrets.HABBLIVE_USERNAME_6 }}
          HABBLIVE_PASSWORD_6: ${{ secrets.HABBLIVE_PASSWORD_6 }}
          HABBLIVE_USERNAME_7: ${{ secrets.HABBLIVE_USERNAME_7 }}
          HABBLIVE_PASSWORD_7: ${{ secrets.HABBLIVE_PASSWORD_7 }}
          HABBLIVE_USERNAME_8: ${{ secrets.HABBLIVE_USERNAME_8 }}
          HABBLIVE_PASSWORD_8: ${{ secrets.HABBLIVE_PASSWORD_8 }}
          HABBLIVE_USERNAME_9: ${{ secrets.HABBLIVE_USERNAME_9 }}
          HABBLIVE_PASSWORD_9: ${{ secrets.HABBLIVE_PASSWORD_9 }}
          HABBLIVE_USERNAME_10: ${{ secrets.HABBLIVE_USERNAME_10 }}
          HABBLIVE_PASSWORD_10: ${{ secrets.HABBLIVE_PASSWORD_10 }}
          HABBLIVE_USERNAME_11: ${{ secrets.HABBLIVE_USERNAME_11 }}
          HABBLIVE_PASSWORD_11: ${{ secrets.HABBLIVE_PASSWORD_11 }}
          # Devido as limitações de IP, recomenda-se apenas logar no máximo em 11 contas.
        run: python persistent_login.py
